package az.edu.ada.wm2.lab4.model;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Objects;
import java.util.UUID;

public class Product {

    private UUID id;
    private String productName;
    private BigDecimal price;
    private LocalDate expirationDate;

    // 1) No-args constructor (id autogenerated)
    public Product() {
        this.id = UUID.randomUUID();
    }

    // 2) Constructor without id (id autogenerated)
    public Product(String productName, BigDecimal price, LocalDate expirationDate) {
        this.id = UUID.randomUUID();
        this.productName = productName;
        this.price = price;
        this.expirationDate = expirationDate;
    }

    // 3) Constructor with all fields (useful for update operations)
    public Product(UUID id, String productName, BigDecimal price, LocalDate expirationDate) {
        this.id = (id == null) ? UUID.randomUUID() : id;
        this.productName = productName;
        this.price = price;
        this.expirationDate = expirationDate;
    }

    // Getters & Setters
    public UUID getId() {
        return id;
    }

    // Optional: keep setter (for updates), but still safe if null is passed
    public void setId(UUID id) {
        this.id = (id == null) ? UUID.randomUUID() : id;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public LocalDate getExpirationDate() {
        return expirationDate;
    }

    public void setExpirationDate(LocalDate expirationDate) {
        this.expirationDate = expirationDate;
    }

    @Override
    public String toString() {
        return "Product{" +
                "id=" + id +
                ", productName='" + productName + '\'' +
                ", price=" + price +
                ", expirationDate=" + expirationDate +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Product)) return false;
        Product product = (Product) o;
        return Objects.equals(id, product.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }
}
